cmd_vel:
    type: geometry_msgs/Twist
    vx: 
        min: -1
        max: 1
        to: linear.x
        default: 0.
    vy: 
        min: -1
        max: 1
        to: linear.y      
    wz: 
        min: -1
        max: 1
        to: angular.z
set_pen:
    type: turtlesim/srv/SetPen
    'off':
        to: 'off'
        default: 0
        min: 0
        max: 1
    red:
        to: 'r'
        default: 255
        min: 0
        max: 255
    green:
        to: 'g'
        default: 0
        min: 0
        max: 255
    blue:
        to: 'b'
        default: 0
        min: 0
        max: 255
    width:
        to: 'width'
        default: 0
        min: 0
        max: 4
