/**:    # those params fit all nodes
  ros__parameters:
    axis_linear:  # Left thumb stick vertical
      x: 1
    scale_linear:
      x: 2.
    scale_linear_turbo:
      x: 4.

    axis_angular:  # Right thumb stick horizontal
      yaw: 3
    scale_angular:
      yaw: 1.

    require_enable_button: False
    enable_button: 2  # Left trigger button
    enable_turbo_button: 5  # Right trigger button
