#!/usr/bin/env python3

import rclpy
from rclpy.node import Node
from geometry_msgs.msg import Twist
from turtlesim.msg import Pose
from turtlesim.srv import SetPen
from math import cos, sin, atan2, pi
from rcl_interfaces.msg import SetParametersResult, ParameterDescriptor, FloatingPointRange

dt = 0.1


class Tracker(Node):
    def __init__(self):
        super().__init__('tracker')
        
        self.target = self.declare_parameter("target", 'turtle1').value

        from time import sleep
        sleep(self.declare_parameter("wait", 1).value + 1)
        
        # no pen
        pen_srv = self.create_client(SetPen, 'set_pen')
        pen_srv.wait_for_service()
        no_pen = SetPen.Request(off = 1)
        res = pen_srv.call_async(no_pen)
        rclpy.spin_until_future_complete(self, res)
        
        # subscribers
        self.pose = None
        self.pose_sub = self.create_subscription(Pose, 'pose', self.get_pose, 10)
        
        self.target_pose = None
        self.target_sub = self.create_subscription(Pose, f'/{self.target}/pose', self.get_target_pose, 10)
        
        self.cmd = Twist()
        self.cmd_vel = self.create_publisher(Twist, 'cmd_vel', 10)

        # gains
        self.Kv = self.declare_bounded_param("Kv", 2., 0., 10., 'Linear gain')
        self.Kw = self.declare_bounded_param("Kw", 2.5, 0., 10., 'Angular gain')
        self.d = self.declare_bounded_param("d", 1., 0., 5., 'Tracking distance')
        self.add_on_set_parameters_callback(self.param_change)
        
        self.timer = self.create_timer(dt, self.compute_cmd)

    def declare_bounded_param(self, name, default, low, high, description = None):
        descr = ParameterDescriptor(
                name = name,
                floating_point_range = [FloatingPointRange(
                    from_value = float(low), to_value = float(high))],
                description = description)
        return self.declare_parameter(name, float(default), descr).value

    def param_change(self, params):

        accept = True
        for param in params:
            self.get_logger().warn('Request: {} -> {}'.format(param.name, param.value))
            if param.value < 0:
                accept = False
            else:
                if param.name == 'Kv':
                    self.Kv = param.value
                elif param.name == 'Kw':
                    self.Kw = param.value
                elif param.name == 'd':
                    self.d = param.value

        return SetParametersResult(successful=accept)
        
    def get_pose(self, msg):
        self.pose = msg
        
    def get_target_pose(self, msg):
        self.target_pose = msg
        
    def compute_cmd(self):
        
        if self.pose is None or self.target_pose is None:
            return
        
        dx = self.target_pose.x - self.pose.x
        dy = self.target_pose.y - self.pose.y
        
        c,s = cos(self.pose.theta), sin(self.pose.theta)
        
        theta = atan2(dy,dx) - self.pose.theta
        theta = (theta+pi) % (2*pi) - pi
        
        self.cmd.linear.x = self.Kv*(dx*c+dy*s-self.d)
        self.cmd.angular.z = self.Kw * theta
        
        self.cmd_vel.publish(self.cmd)


rclpy.init()
tracker = Tracker()

rclpy.spin(tracker)

# clean exit on Ctrl-C
tracker.destroy_node()
rclpy.shutdown()
